version: "3.9"
services:
  nodeos:
    image: docker.io/eosio/eos:develop
    command: 
      - nodeos 
      - --plugin
      - eosio::producer_plugin 
      - --plugin 
      - eosio::chain_api_plugin 
      - --plugin 
      - eosio::http_plugin 
      - --plugin 
      - eosio::producer_api_plugin 
      - --chain-state-db-size-mb 
      - "65536"
      - --plugin 
      - eosio::state_history_plugin  
      - --state-history-endpoint
      - 0.0.0.0:8080
      - --http-server-address 
      - 0.0.0.0:8888
      - --trace-history 
      - --chain-state-history
      - --disable-replay-opts 
      - --p2p-peer-address=${PEER_ADDR:-seed.testnet.eos.io:9876}
      - --snapshot 
      - /snapshots/snapshot.bin
    volumes:
      - ./${SNAPSHOT_FILE:-snapshot.bin}:/snapshots/snapshot.bin
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
  fill-pg:
    image: "eosio/history-tools:935650a6fb9ca596affe0a3c42e6a1966675061d"
    command: 
      - ./fill-pg
      - --fpg-create
      - --fill-connect-to=nodeos:8080
    environment:
      - PGUSER=postgres
      - PGPASSWORD=password 
      - PGHOST=postgres
    restart: always
    depends_on: 
      - postgres
      - nodeos
  postgres-query:
    image: postgres
    command:
      - db-query.sh
    environment:
      - PGUSER=postgres
      - PGPASSWORD=password 
      - PGHOST=postgres
    depends_on: 
      - postgres
    

 
     
